#!/bin/sh

if [ $# -ne 1 ]; then
    echo "Usage: $0 {start|stop}"
    exit 1
fi

case "$1" in
    start)
        start-stop-daemon --start --exec /usr/bin/aesdsocket -- -d
        if [ $? -eq 0 ]; then
            echo "aesdsocket started"
        else
            echo "aesdsocket failed to start"
            exit 1
        fi
        ;;
    stop)
        start-stop-daemon --stop --name aesdsocket --signal TERM
        if [ $? -eq 0 ]; then
            echo "aesdsocket stopped"
        else
            echo "aesdsocket failed to stop"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
    esac

exit $?